replicaCount: 3

image:
  repository: ghcr.io/reseaux3d-sudo/nginx-demo-repo
  tag: 936cc831ab0813c85f3be5d113a44d0fd325d704
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
