replicaCount: 3

image:
  repository: ghcr.io/reseaux3d-sudo/nginx-demo-repo
  tag: a8863d99989b41e02b92a84be0716b2a034e7f0e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
